### ISSUE TITLE
Incompatible with enUS WoW client

### ISSUE THREAD

**Issue by Tahiku** [RomanSpector/AbbreviatedStatus#5]
As the title says, your AddOn is sadly incompatible with the enUS client currently, the settings are left with "??" as text, instead of Russian text and / or English translated text :

![AbbreviatedStatusTextIncompatible 1](https://user-images.githubusercontent.com/38655313/147400570-6aaf5c04-35d2-4a22-91d2-08f3f7f51632.png)
![AbbreviatedStatusTextIncompatible 2](https://user-images.githubusercontent.com/38655313/147400574-05953f0a-5156-48b4-ac30-df30d2e98972.png)
(

**Comment by Tahiku** [comment]
Nvm, the fix was simply to remove the RU file, thanks anyway & great AddOn :)

**Comment by BannZay** [comment]
@Tahiku FYI the problem was recently fixed by 46a788d21d19509ad363f834fb961f034e1d12ea
